create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'admin' check (role = 'admin'),
    created_at timestamptz not null default now()
);

create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    external_user_id bigint,
    username text not null unique,
    password_hash text,
    allowed_minutes integer not null default 0 check (allowed_minutes >= 0),
    role text not null default 'user' check (role in ('user', 'admin')),
    is_active boolean not null default true,
    is_local_only boolean not null default false,
    is_consumed boolean not null default false,
    deactivation_pending boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.users(id) on delete set null,
    username text not null,
    start_time timestamptz not null default now(),
    end_time timestamptz,
    allowed_minutes integer not null default 0,
    used_seconds integer not null default 0 check (used_seconds >= 0),
    status text not null default 'active',
    created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_user_id uuid references auth.users(id) on delete set null,
    action text not null,
    entity_type text not null,
    entity_id text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists users_username_idx on public.users (username);
create index if not exists users_active_idx on public.users (is_active, username);
create index if not exists sessions_start_time_idx on public.sessions (start_time desc);
create index if not exists sessions_user_id_idx on public.sessions (user_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admin_profiles
        where user_id = auth.uid()
          and role = 'admin'
    );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.admin_profiles enable row level security;
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists admin_profiles_self_select on public.admin_profiles;
create policy admin_profiles_self_select
on public.admin_profiles for select
to authenticated
using (user_id = auth.uid());

drop policy if exists users_admin_all on public.users;
create policy users_admin_all
on public.users for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists sessions_admin_select on public.sessions;
create policy sessions_admin_select
on public.sessions for select
to authenticated
using (public.is_admin());

drop policy if exists audit_logs_admin_select on public.audit_logs;
create policy audit_logs_admin_select
on public.audit_logs for select
to authenticated
using (public.is_admin());

drop policy if exists audit_logs_admin_insert on public.audit_logs;
create policy audit_logs_admin_insert
on public.audit_logs for insert
to authenticated
with check (public.is_admin() and actor_user_id = auth.uid());

comment on table public.users is 'Central user records migrated from local SQLite/Google Sheets.';
comment on table public.sessions is 'Usage history snapshots shared by all TimeLockApp devices.';
comment on table public.audit_logs is 'Immutable admin actions recorded by the Admin Web server.';

-- After creating the first Supabase Auth user, run:
-- insert into public.admin_profiles (user_id)
-- select id from auth.users where email = 'admin@example.com';
